"""更改文章数据模型

Revision ID: bac6dcae778e
Revises: 28d9974af759
Create Date: 2018-04-27 21:24:39.857825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac6dcae778e'
down_revision = '28d9974af759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('createTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'createTime')
    # ### end Alembic commands ###
