"""empty message

Revision ID: d599b721b7aa
Revises: 
Create Date: 2018-04-22 16:25:55.491956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd599b721b7aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', sa.String(length=50), nullable=True))
    op.drop_column('Users', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('user_name', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###
